name: Compress and Release

on:
  push:
    branches:
      - main
      - pre-45

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Get Hash
      run: |
        echo ${{ github.event.head_commit.id }}
        echo git rev-parse --short ${{ github.event.head_commit.id }}
        echo "hash=$(git rev-parse --short ${{ github.event.head_commit.id }})" >> "$GITHUB_ENV"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.hash }}
        release_name: Autorelease ${{ env.hash }}
        draft: false
        prerelease: false
        body: |
          Please see [Install From Source](https://github.com/Vishram1123/gjs-osk?tab=readme-ov-file#install-from-source) instructions for installation
          
          > ${{ github.ref_name }}: ${{ github.event.head_commit.message }}
    
    - name: Compress directory (main)
      run: |
        cd gjsosk@vishram1123.com && zip -r ../gjsosk@vishram1123_main.zip ./*

    - name: Upload Release Asset (main)
      id: upload-release-asset-main
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gjsosk@vishram1123_main.zip
        asset_name: gjsosk@vishram1123_main.zip
        asset_content_type: application/zip

    - name: Checkout pre-45 branch
      uses: actions/checkout@v2
      with:
        ref: 'pre-45'
        
    - name: Compress directory (pre-45)
      run: |
        cd gjsosk@vishram1123.com && zip -r ../gjsosk@vishram1123_pre-45.zip ./*

    - name: Upload Release Asset (pre-45)
      id: upload-release-asset-pre-45
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./gjsosk@vishram1123_pre-45.zip
        asset_name: gjsosk@vishram1123_pre-45.zip
        asset_content_type: application/zip
